stages:
  - test
  - build
  - deploy

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME

test:
  stage: test
  image: logomotion/code-quality
  script: 
    - phpcs --standard=PSR2 ./src
    - security-checker security:check
    - phpcpd src
    - phpmd src text unusedcode

build:
  stage: build
  image: docker:git
  services:
  - docker:dind
  before_script:
  - apk add --no-cache py-pip
  - pip install docker-compose
  script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  - docker build -t registry.gitlab.com/logomotion/cartron-www .
  - docker push registry.gitlab.com/logomotion/cartron-www
deploy_dev:
  stage: deploy
  image: php:7-cli-alpine
  before_script:
    - apk add --update git openssh-client
    - mkdir -p ~/.ssh && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
  environment:
    name: dev
    url: https://dev.cartron.fr
  script:
        - curl -L https://deployer.org/releases/v6.4.3/deployer.phar > /usr/local/bin/deployer && chmod +x /usr/local/bin/deployer
        - deployer -f=deploy/deploy.php deploy dev
deploy_staging:
  stage: deploy
  image: php:7-cli-alpine
  before_script:
    - apk add --update git openssh-client
    - mkdir -p ~/.ssh && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
  environment:
    name: staging
    url: https://staging.cartron.fr
  script:
        - curl -L https://deployer.org/releases/v6.4.3/deployer.phar > /usr/local/bin/deployer && chmod +x /usr/local/bin/deployer
        - deployer -f=deploy/deploy.php deploy staging
