version: '3'
 
services:
    apache:
        container_name: ${COMPOSE_PROJECT_NAME}_apache_con
        image: logomotion/httpd
        volumes:
            - ./app/logs/apache:/usr/local/apache2/logs
            - .:/usr/local/apache2/htdocs
        ports:
            - ${APACHE_EXPOSED_PORT}:80
        networks:
            public_net:
                ipv4_address: ${APACHE_IP}
        environment:
            - PHP_IP=${PHP_IP}
            - WEB_USER=${WEB_USER}
            - WEB_GROUP=${WEB_GROUP}
    mysql:
        container_name: ${COMPOSE_PROJECT_NAME}_mysql_con
        image: mysql:5.6
        volumes:
            - ./app/logs/mysql:/var/log/mysql
            - ./database:/var/lib/mysql
        networks:
            public_net:
                ipv4_address: ${MYSQL_IP}
        environment:
            - MYSQL_ROOT_PASSWORD=mysql
    php:
        container_name: ${COMPOSE_PROJECT_NAME}_php_con
        image: logomotion/php:5.6
        working_dir: /srv/app
        volumes:
            - .:/srv/app
            - ./app/logs/php:/usr/local/etc/logs
        depends_on:
            - apache
            - mysql
        networks:
            public_net:
                ipv4_address: ${PHP_IP}
        environment:
            - APACHE_IP=${APACHE_IP}
            - WEB_USER=${WEB_USER}
            - WEB_GROUP=${WEB_GROUP}
        external_links:
            - mysql-57:db
    phpmyadmin:
        container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin_con
        image: phpmyadmin/phpmyadmin:latest
        networks: 
            - public_net
        ports:
            - ${PHPMYADMIN_PORT}:80
        links:
            - mysql:db
 
networks:
    public_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK_SUBNET}
