parameters:
    database_driver: pdo_mysql
    database_host: db
    database_port: null
    database_name: cartron
    database_user: root
    database_password: mysql

    mailer_transport:  smtp
    mailer_host: 'smtp:2525'
    mailer_user: smtp
    mailer_password: smtp

    locale: en
    secret: ThisTokenIsNotSoSecretChangeIt
