parameters:
    database_driver:   pdo_mysql
    database_host:     192.168.10.10
    database_port:     ~
    database_name:     local_cartron
    database_user:     homestead
    database_password: secret

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
