app:
    resource: '@AppBundle/Controller/'
    type: annotation
site_admin:
    resource: '@AppBundle/Controller/Admin'
    type: annotation
    prefix:   /admin
pages:
    resource: '@AppBundle/Controller/PageController.php'
    type: annotation