parameters:
#    site_cartron.example.class: Site\CartronBundle\Example

services:
#    site_cartron.example:
#        class: %site_cartron.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
