site_admin_homepage:
    pattern:  /
    defaults: { _controller: SiteAdminBundle:Default:index }
    
site_admin_homepage_add_article:
    pattern:  /manageArticle
    defaults: { _controller: SiteAdminBundle:Default:ajouterArticle }

site_admin_homepage_add_video:
    pattern:  /manageVideoHp
    defaults: { _controller: SiteAdminBundle:Default:ajouterVideoHp }

site_admin_collection:
    pattern:  /collection
    defaults: { _controller: SiteAdminBundle:Default:collection }


site_admin_add_collection:
    pattern:  /manageCollection
    defaults: { _controller: SiteAdminBundle:Default:ajouterCollection }

site_admin_sous_menu:
    pattern:  /sousMenu
    defaults: { _controller: SiteAdminBundle:Default:sousMenu }


site_admin_add_sous_menu:
    pattern:  /manageSousMenuCollection
    defaults: { _controller: SiteAdminBundle:Default:ajouterSousMenu }


site_admin_degustation:
    pattern:  /degustation
    defaults: { _controller: SiteAdminBundle:Default:degustation }


site_admin_add_degustation:
    pattern:  /manageDegustation
    defaults: { _controller: SiteAdminBundle:Default:ajouterDegustation }
    
site_admin_sous_menu_degustation:
    pattern:  /sousMenuDegustation
    defaults: { _controller: SiteAdminBundle:Default:sousMenuDegustation }


site_admin_add_sous_menu_degustation:
    pattern:  /manageSousMenuDegustation
    defaults: { _controller: SiteAdminBundle:Default:ajouterSousMenuDegustation }

site_admin_produit_pro:
    pattern:  /{id}/{type}/espace_pro_produits
    defaults: { _controller: SiteAdminBundle:Default:produit }


site_admin_manage_produits_pro:
    pattern:  /espace_pro_manageProduits
    defaults: { _controller: SiteAdminBundle:Default:ajouterProduit }

site_admin_manage_degustation_pro:
    pattern:  /espace_pro_manageDegustation
    defaults: { _controller: SiteAdminBundle:Default:ajouterProduit }

site_admin_degustation_pro:
    pattern:  /espace_pro_degustation
    defaults: { _controller: SiteAdminBundle:Default:degustationPro }

site_admin_sous_menu_produit_pro:
    pattern:  /espace_pro_sous_menu_produit
    defaults: { _controller: SiteAdminBundle:Default:sousMenuProduit }
    
site_admin_manage_sous_menu_produit_pro:
    pattern:  /espace_pro_manage_sous_menu_produit
    defaults: { _controller: SiteAdminBundle:Default:ajouterSousMenuProduit }

site_admin_manage_sous_menu_degustation_pro:
    pattern:  /espace_pro_manage_sous_menu_degustation_pro
    defaults: { _controller: SiteAdminBundle:Default:ajouterSousMenuDegustationPro }
 

site_admin_menu_pro:
    pattern:  /espace_pro_menu_pro
    defaults: { _controller: SiteAdminBundle:Default:autreMenu }

site_admin_manage_menu_pro:
    pattern:  /espace_pro_manage_menu_pro
    defaults: { _controller: SiteAdminBundle:Default:ajouterAutreMenu }

listes_pays:
    pattern:  /pays
    defaults: { _controller: SiteAdminBundle:Default:pays }  
    
ajout_pays:
    pattern:  /managePays
    defaults: { _controller: SiteAdminBundle:Default:ajouterPays } 
    
supprimer:
    pattern:  /supprimer/{table}/{id}
    defaults: { _controller: SiteAdminBundle:Default:supprimer }

login:
    pattern:  /login
    defaults: { _controller: SiteAdminBundle:Default:login }

logout:
    pattern:  /logout
    defaults: { _controller: SiteAdminBundle:Default:logout }